# Tested usage:
# conda build ./conda-recipes/cuda-tile --python=3.12 -c defaults -c conda-forge
#
# NOTES: conda-forge needed for newer nanobind

{% set version = "13.1.3" %}

package:
  name: cuda_tile_mlir
  version: {{ version }}

source:
  - git_url: https://github.com/NVIDIA/cuda-tile/
    git_rev: 8a775693b18303d6c696be6ffd06dadad1b32a8e
    git_depth: 1
  - path: setup.py
  
build:
  number: 0
requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - nanobind >=2.9  # currently need conda-forge
    - pybind11
    - python
  host:
    - setuptools
    - python 
    - zlib                   
    - zstd                   
  run:
    - python
test:
  imports:
    - cuda_tile

about:
  home: https://github.com/NVIDIA/cuda-tile
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  summary: cuda-tile (MLIR)

extra:
  recipe-maintainers:
    - sklam
    